// <auto-generated />
using Learning_REST.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learning_REST.Migrations
{
    [DbContext(typeof(Learning_RESTContext))]
    [Migration("20250712005800_book data added")]
    partial class bookdataadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Learning_REST.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Genres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumPages")
                        .HasColumnType("int");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Follett, Ken",
                            Genres = "[\"Historical Fiction\"]",
                            NumPages = 806,
                            Title = "The Pillars of the Earth",
                            YearPublished = 1989
                        },
                        new
                        {
                            Id = 2,
                            Author = "Le Guin, Ursula K.",
                            Genres = "[\"Science Fiction\"]",
                            NumPages = 286,
                            Title = "The Left Hand of Darkness",
                            YearPublished = 1969
                        },
                        new
                        {
                            Id = 3,
                            Author = "Flynn, Gillian",
                            Genres = "[\"Psychological Thriller\",\"Southern Gothic\",\"Mystery\"]",
                            NumPages = 0,
                            Title = "Sharp Objects",
                            YearPublished = 2006
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jemisin, N. K.",
                            Genres = "[\"Science Fantasy\"]",
                            NumPages = 512,
                            Title = "The Fifth Season",
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 5,
                            Author = "Isaacson, Walter",
                            Genres = "[\"Biography\"]",
                            NumPages = 656,
                            Title = "Steve Jobs",
                            YearPublished = 2011
                        },
                        new
                        {
                            Id = 6,
                            Author = "Moyes, Jojo",
                            Genres = "[\"Romance\",\"Fiction\"]",
                            NumPages = 480,
                            Title = "Me Before You",
                            YearPublished = 2012
                        },
                        new
                        {
                            Id = 7,
                            Author = "Stearns, Marshall W.",
                            Genres = "[\"Music\",\"History\",\"Nonfiction\"]",
                            NumPages = 367,
                            Title = "The Story of Jazz",
                            YearPublished = 1970
                        },
                        new
                        {
                            Id = 8,
                            Author = "King, Stephen",
                            Genres = "[\"Horror\",\"Thriller\",\"Dark Fantasy\"]",
                            NumPages = 1138,
                            Title = "It",
                            YearPublished = 1986
                        },
                        new
                        {
                            Id = 9,
                            Author = "Dugoni, Robert",
                            Genres = "[\"Historical Fiction\"]",
                            NumPages = 448,
                            Title = "The Extraordinary Life of Sam Hell",
                            YearPublished = 2018
                        },
                        new
                        {
                            Id = 10,
                            Author = "Livio, Mario",
                            Genres = "[\"Science\",\"Nonfiction\",\"Mathematics\",\"History\",\"Philosophy\"]",
                            NumPages = 294,
                            Subtitle = "The Story of Phi, the World's Most Astonishing Number",
                            Title = "The Golden Ratio",
                            YearPublished = 2002
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
